server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka/


#eureka.client.register-with-eureka 表示是否将自己注册到Eureka Server，默认为true。因为当前应用就是Eureka Server，所以需要设置成false。
#eureka.client.fetch-registry 表示是否从Eureka Server获取注册信息，默认为true。因为本例是一个单点的Eureka Server，不需要同步其他Eureka Server节点数据，所以设置为false。
#eureka.client.service-url.defaultZone 设置的是与Eureka Server的交互地址，查询和注册服务都依赖这个地址，如果有多个可以使用英文逗号分隔。

